### ISSUE TITLE
Are there any special instructions for initialising beeline when using waitress server?

### ISSUE THREAD

**Issue by jarshwah** [honeycombio/beeline-python#134]
[Waitress](https://docs.pylonsproject.org/projects/waitress/en/stable/) is an increasingly popular application server in cloud contexts (google cloud run, for example) as it buffers incoming requests and can be used without being frontend by Nginx or some other buffering server.

https://docs.honeycomb.io/getting-data-in/python/beeline/#using-the-python-beeline-with-python-pre-fork-models mentions a few different ways to initialise the library in a pre-fork environment.

I don't believe waitress uses a forking model. My understanding (basic) is that it uses asyncio to buffer individual requests, and a threadpool to execute the application.

Does the beeline need to be initialised in a special way with Waitress?

**Comment by vreynolds** [comment]
We're not aware of any specific requirements for `waitress`. If you're not using a pre-fork model, no special handling should be necessary.
