### ISSUE TITLE
Outgoing request instrumentation doesn't need to import *

### ISSUE THREAD

**Issue by mattbennett** [honeycombio/beeline-python#161]
The [beeline docs](https://docs.honeycomb.io/getting-data-in/python/beeline/#instrumenting-outgoing-requests) show this line for instrumenting outgoing requests:

```
from beeline.patch.requests import *
```

This isn't necessary and caused problems for us in an app that had a variable which got shadowed by this import.

It's sufficient and safer to run simply:

```
from beeline.patch.requests import requests
```

**Comment by vreynolds** [comment]
Updated! Thank you for the suggestion.
