### ISSUE TITLE
WSGIMiddlware has bad or confusing imports

### ISSUE THREAD

**Issue by sebastiandev** [honeycombio/beeline-python#163]
We can see [these imports](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/flask/__init__.py#L6)
```
from beeline.propagation import Request   <---- Request
from flask import current_app, signals
# needed to build a request object from environ in the middleware
from werkzeug.wrappers import Request   <---- Request again, overriding it
```

Then a request is instantiated  [here](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/flask/__init__.py#L41)
```
req = Request(environ, shallow=True)
```

It looks like the import from the propagate module is wrong because it doesn't take parameters. It has to be using the werkzeug one. But the built instance is not really used, so, can it be removed along with the imports to avoid confusion?

**Comment by MikeGoldsmith** [comment]
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
