### ISSUE TITLE
Django async / channels support

### ISSUE THREAD

**Issue by Ian-Foote** [honeycombio/beeline-python#165]
I've been working on a project using Django channels for websockets. Unfortunately, I have not been able to find a tool that will allow me to profile the performance in a live or live-like environment. I've heard a lot of good things about honeycomb and would love to use it here but, as you say in the docs, ["The Python Beeline does not currently support asyncio-based frameworks"](https://docs.honeycomb.io/getting-data-in/python/beeline/#requirements).

I notice there is the [`aiotrace` module](https://github.com/honeycombio/beeline-python/blob/main/beeline/aiotrace.py) - is it still possible to instrument Django channels at a lower level, or are there other blockers? Some guidance here would be appreciated.

**Comment by JamieDanielson** [comment]
Hello,

We are trimming our OSS backlog. We are closing this issue as it is a low priority for us to fix in the beeline, but as a follow-up we are going to contribute some documentation upstream for OpenTelemetry best practices for async instrumentation in Python.
