### ISSUE TITLE
'WSGIRequest' object has no attribute 'headers'

### ISSUE THREAD

**Issue by nicholasgcoles** [honeycombio/beeline-python#169]
After bumping up to `2.17.0` I am running into the following error `'WSGIRequest' object has no attribute 'headers'`.

I think [this PR](https://github.com/honeycombio/beeline-python/pull/160/files) caused the regression.

My requirements.txt
```
...
Django==2.0
...
honeycomb-beeline>=2.16.2,<3.0.0
```

**Comment by JamieDanielson** [comment]
It looks like Django 2.0 is past its end of life and we missed that this would be breaking for this version of Django. This change was made to address a deprecated method in Django 3.1. At this point it seems best for us to update our beeline to be more explicit that we will support from a later version of Django, at least starting with Django 3.1 but we will test a bit further to see if that's feasible or if a more current version is required for a minimum.

I've created a new issue #225 to update our minimum supported Django version.
