### ISSUE TITLE
Django query tracing only logs duration for successful queries.

### ISSUE THREAD

**Issue by sjoerdjob** [honeycombio/beeline-python#206]
Django query tracing only logs duration for successful queries.

**Versions**

- Python: any
- Beeline: latest

**Steps to reproduce**

1. Use the Django middleware.
2. Make a query that fails (lock wait timeout, query for missing table, unique constraint violation)
3. Observe the generated span, check whether it has a `db.duration` field.

[easy way to observe through the Honeycomb UI: VISUALIZE(db.duration) WHERE(db.error_detail exists)]

**Additional context**

**Comment by vreynolds** [comment]
Thanks for reporting! Yep, looks like `db.duration` is only added if there's no errors: https://github.com/honeycombio/beeline-python/blob/90509bbd63f0db60e0495ea171ac5019adb232f4/beeline/middleware/django/__init__.py#L62

I don't see a reason not to add it regardless of error.

**Comment by pkanal** [comment]
Hello,
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
