### ISSUE TITLE
Do we really wanna hide all exceptions, i think this is breaking some code of mine

### ISSUE THREAD

**Issue by posix4e** [honeycombio/beeline-python#31]
https://github.com/honeycombio/beeline-python/blob/cf6272bf5d8e21c6e31829baaca316dd5174759a/beeline/patch/requests.py#L18

**Comment by tredman** [comment]
Hey,

The intent here is to catch any exceptions caused by the beeline code when marshaling the trace context:

```
b = beeline.get_beeline()
        if b:
            context = b.tracer_impl.marshal_trace_context()
            if context:
                b.log("requests lib - adding trace context to outbound request: %s", context)
                instance.headers['X-Honeycomb-Trace'] = context
            else:
                b.log("requests lib - no trace context found")
```
Worst case, we catch any exceptions we cause and just let the `requests` lib work as normal.
This shouldn't eat any application errors... can you point at some code/issue you think is affected by this?

**Comment by posix4e** [comment]
Not yet

**Comment by posix4e** [comment]
Actually I have an example where if i include your libary request.post to a url always returns none now

**Comment by posix4e** [comment]
I switched the code to
```
def request(_request, instance, args, kwargs):
    try:
        b = beeline.get_beeline()
        if b:
            context = b.tracer_impl.marshal_trace_context()
            if context:
                b.log("requests lib - adding trace context to outbound request: %s", context)
                instance.headers['X-Honeycomb-Trace'] = context
            else:
                b.log("requests lib - no trace context found")
    finally:
        _request(*args, **kwargs)

```
And it didn't fix anything

**Comment by posix4e** [comment]
```

def request(_request, instance, args, kwargs):

    try:
        b = beeline.get_beeline()
        if b:
            context = b.tracer_impl.marshal_trace_context()
            if context:
                b.log("requests lib - adding trace context to outbound request: %s", context)
                instance.headers['X-Honeycomb-Trace'] = context
            else:
                b.log("requests lib - no trace context found")
    finally:
        return _request(*args, **kwargs)
```
Works fine however

**Comment by tredman** [comment]
Oh! Good catch. yeah we should be returning the value of `_request(*args, **kwargs)` or we will break functionality. I'll push a quick fix to master so you can keep playing off of master. I should have version 2.0.0 of the beeline published in the next day or so.

**Comment by tredman** [comment]
https://github.com/honeycombio/beeline-python/commit/8f39baa4ce125d7f1c99d39fb415926a41a49e6a - should fix things up for you.

**Comment by posix4e** [comment]
Can we add a test?
