### ISSUE TITLE
Uninitialised tracer raises when not being initialised

### ISSUE THREAD

**Issue by mariokostelac** [honeycombio/beeline-python#51]
I am looking here for either guidance or a fix.

I have a Flask app that runs in different environments, one of them being jupyter notebooks. As you could imagine, Jupyter notebook loads part of the app, crashing when tracer gets called, if uninitialised. I'd like to provide an experience where a developer does not have to load honeycomb setup in Jupyter to experiment with the code.

Here is the little helper package I wrote for myself to introduce a nice decorator for functions I want to trace::
```python
import beeline
import functools
import config
import os

from beeline.middleware.flask import HoneyMiddleware

tracer = beeline.tracer
add_field = beeline.add_field
add_trace_field = beeline.add_trace_field


def init(app):
    beeline.init(writekey=config.HONEYCOMB_API_KEY, dataset='<redacted>', service_name='<redacted>', presend_hook=presend)
    HoneyMiddleware(app, db_events=False)


def presend(fields):
    fields['pid'] = os.getpid()


def traced(name):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            with tracer(name):
                return func(*args, **kwargs)
        return wrapper
    return decorator

```

Exception
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-edff33869504> in <module>()
      1 import model
----> 2 model.load_bot_model(6)

~/SageMaker/team-ml/sth/src/honeycomb.py in wrapper(*args, **kwargs)
     24         @functools.wraps(func)
     25         def wrapper(*args, **kwargs):
---> 26             with tracer(name):
     27                 return func(*args, **kwargs)
     28         return wrapper

~/anaconda3/lib/python3.6/site-packages/beeline/__init__.py in tracer(name, trace_id, parent_id)
    361     - `name`: a descriptive name for the this trace span, i.e. "database query for user"
    362     '''
--> 363     return _GBL.tracer(name=name, trace_id=trace_id, parent_id=parent_id)
    364 
    365 def start_trace(context=None, trace_id=None, parent_span_id=None):

AttributeError: 'NoneType' object has no attribute 'tracer'
```

I can see two different solutions here:
- changing beeline.tracer to not fail when it's not initialised
- set the tracer inside `init` to the beeline.tracer, otherwise have just a fake one.

What are your thoughts?

**Comment by tredman** [comment]
Do you want to avoid calling `beeline.init` at all, or are you just trying to avoid sending events to honeycomb in a dev environment?


For the latter: You could initialize the beeline with dummy values for `writekey` and `dataset`, then override the transmission to send to stderr. There's an example here: https://docs.honeycomb.io/beeline/python/#customizing-event-transmission

If you want to avoid writing *anything* you could also override the transmitter to write to /dev/null.

```
import beeline
import libhoney
import os
from libhoney.transmission import FileTransmission

beeline.init(writekey='yourwritekey', transmission_impl=FileTransmission(output=open(os.devnull, 'w'))
```

(we really should add a NullTransmission to libhoney, for when absolutely no output is desired.)

If you are trying to avoid calling `beeline.init` at all - I think we would need to update `beeline.tracer` to work in the case that it's not initialized. Funnily enough, in version 2.4.1, we added a `traced` function wrapper that *does* work if the beeline is not initialized - you might try that if you just want to use the wrapper. Docs are here: https://docs.honeycomb.io/beeline/python/#using-traces - see the section "using a decorator".

Let me know if this helps.

**Comment by mariokostelac** [comment]
> Do you want to avoid calling beeline.init at all, or are you just trying to avoid sending events to honeycomb in a dev environment?

Sorry for not explaining the problem clearly enough. I am trying to do something different actually. I am trying to avoid the need to call beeline.init() in some environments and still have decorated functions work properly.

> Funnily enough, in version 2.4.1, we added a traced function wrapper that does work if the beeline is not initialized - you might try that if you just want to use the wrapper. Docs are here: https://docs.honeycomb.io/beeline/python/#using-traces - see the section "using a decorator".
Let me know if this helps.

It seems to be exactly what I need! Will upgrade now (running 2.3.0) and remove my homebrew decorators.

**Comment by tredman** [comment]
Btw https://github.com/honeycombio/beeline-python/pull/53 will fix the issue with the context manager. When #54 lands I'll cut version 2.4.4 with the changes.

**Comment by mariokostelac** [comment]
> Btw #53 will fix the issue with the context manager.

👏

**Comment by mariokostelac** [comment]
Fixed.
