### ISSUE TITLE
TypeError('Object of type datetime is not JSON serializable')

### ISSUE THREAD

**Issue by fajpunk** [honeycombio/beeline-python#58]
I just tried to set up honeycomb in my relatively simple (admin site only) Django 2.1.5 app with a Postgres 11.1 DB running locally, configured with the middleware added, and:

```python
from django.apps import AppConfig  # type: ignore
from django.conf import settings  # type: ignore
import beeline  # type: ignore


class LettersConfig(AppConfig):
    name = "letters"

    def ready(self):
        beeline.init(
            writekey=settings.HONEYCOMB_WRITE_KEY,
            dataset="artandtybie",
            service_name="my-app-name",
            debug=True,
        )
```

I have so far not received any events in the Honeycomb UI, and see a lot of these messages in the logs:

```2019-02-09 04:06:31,892 - honeycomb-sdk-xmit - DEBUG - enqueuing response = {'status_code': 0, 'body': '', 'error': TypeError('Object of type datetime is not JSON serializable'), 'duration': 5.233049392700195, 'metadata': None}```

Maybe they're coming from trying to serialize query args for a query against a model with a date field?

```2019-02-09 04:06:31,633 - honeycomb-sdk - DEBUG - send enqueuing event ev = {'service_name': 'my-app-name', 'meta.beeline_version': '2.4.6', 'meta.local_hostname': 'localhost.localdomain', 'name': 'django_postgresql_query', 'trace.trace_id': '58a65be3-31a9-4c70-a9cd-8068459d30ef', 'trace.parent_id': '474479f5-e10b-474c-94f3-4830afc4e116', 'trace.span_id': '2abbba28-578c-4b0e-b27c-f9844c93df85', 'type': 'db', 'db.query': 'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > %s AND "django_session"."session_key" = %s)', 'db.query_args': (datetime.datetime(2019, 2, 9, 4, 6, 31, 626689, tzinfo=<UTC>), 'xxxxxxxx'), 'db.duration': 2.083, 'db.last_insert_id': 0, 'db.rows_affected': 1, 'duration_ms': 2.4789999999999996}```

Am I configuring this Beeline correctly?

**Comment by tredman** [comment]
Thanks for the report! Yes I think you are configuring the beeline correctly - unfortunately the default json encoder chokes on datetime values. It can be fixed but we'll need to address this in the underlying `libhoney-py` library and then bump the package here to use that version. This shouldn't take long and I can have a fix early in the week. I'll update you here.

**Comment by tredman** [comment]
@fajpunk - 2.4.7 includes a fix for this - can you update your beeline version and let me know how it goes?
