### ISSUE TITLE
[flask-sqlalchemy] db.query_args appears as the param names, not param values

### ISSUE THREAD

**Issue by benregn** [honeycombio/beeline-python#62]
The problem seems to be that the `parameters` argument to the `before_cursor_execute` listener is almost always (maybe always) a dict in my project. Beeline always treats it as if it's a list: https://github.com/honeycombio/beeline-python/blob/634a567/beeline/middleware/flask/__init__.py#L115.

Quote from the docs about the `parameters` argument:
> Dictionary, tuple, or list of parameters being passed to the execute() or executemany() method of the DBAPI cursor. In some cases may be None.

**Comment by tredman** [comment]
Hey! Sorry for the delay, but I haven't forgotten about this. I'll take a look shortly and get back to you.

**Comment by tredman** [comment]
This should be fixed in 2.5.1 of the beeline, please update when you get a chance and let us know if you still see any issues.
