### ISSUE TITLE
Beeline prevents sentry.io from reporting

### ISSUE THREAD

**Issue by fitzoh** [honeycombio/beeline-python#71]
Issue created in the sentry repository @ getsentry/sentry-python#442

Details:
I'm activating sentry in the top of settings.py ([docs](https://docs.sentry.io/platforms/python/django/))
```
sentry_sdk.init(
    dsn=dsn,
    environment=env,
    integrations=[DjangoIntegration()],
)
```

beeline is being initialized in the gunicorn config file ([docs](https://docs.honeycomb.io/getting-data-in/python/beeline/#gunicorn))
```
def post_worker_init(worker):
    beeline.init(
        writekey=honeycomb_key,
        dataset=dataset,
        service_name=service
    )
```

I can manually send errors to sentry, but the automatic error reporting doesn't work unless honeycomb is removed.

Partially redacted requirements.txt
```
Django~=2.1.9
djangorestframework~=3.9.1
gunicorn~=19.9.0
sentry-sdk~=0.10.2
honeycomb-beeline~=2.6.1
libhoney~=1.8.0
statsd~=3.3.0
```

**Comment by tredman** [comment]
Hey, thanks for the report. I am looking into this. I am not aware of any obvious places these libraries would conflict so I will need to spend some time reproducing the problem. We're sentry customers as well so I should be able to test this out.

When you say you removed Honeycomb and Sentry worked again, did you just remove the call to `beeline.init` or did you remove the middleware setting (below) in your django settings.py? Or both?

```
MIDDLEWARE = [
    ...
    'beeline.middleware.django.HoneyMiddleware',
    ...
]
```

**Comment by tredman** [comment]
I tried to reproduce this locally with the beeline, sentry SDK, django, and gunicorn versions above. I was able to see instrumentation in Honeycomb, and when I generated an ISE with an unhandled exception (`raise Exception("foo")` at an arbitrary point in the code, the error event made it to Sentry. When you refer to automatic error reporting, is there a specific type of error that isn't getting through? Could be that I am just testing the wrong thing.

**Comment by fitzoh** [comment]
Disregard, I'm dumb.


So I think honeycomb *was* killing sentry reporting, but it was because I missed the gevent monkeypatch warnings and was itself blowing up due to RecursionErrors.

Fixing the monkeypatching issue seems to get everything working.

**Comment by danyelf** [comment]
Thanks for the followup! Glad you caught it.
