### ISSUE TITLE
Allow easier tweaking of context in Django middleware

### ISSUE THREAD

**Issue by sjoerdjob** [honeycombio/beeline-python#72]
As seen in https://github.com/honeycombio/beeline-python/blob/9c20f68d96903e58908be9de75b4666a41dafc89/beeline/middleware/django/__init__.py#L65, the data in the event context is hardcoded.

I think it would be very beneficial to have some way to override the data in the context without having to re-define `create_http_event` completely.

If the contents of the `context=` parameter could be moved to a separate function, it would be easier to override without also having to re-implement the `start_trace`...`finish_trace`.

**Comment by tredman** [comment]
Fixed in #73  I think.
