### ISSUE TITLE
Beeline middleware causes some specific requests to skip parsers & potentially other middleware

### ISSUE THREAD

**Issue by tarikozket** [honeycombio/beeline-python#74]
One of the endpoints we implemented on our Django rest framework application has `POST` method with `multipart/form-data` content type. We also utilize a parser which converts `camelCase` fields in incoming requests to `snake_case` before they hit the `view`s.

That one endpoint started failing right after integrating Beeline. Actually, it still receives the request, but when you look into the request, you see that it didn't get modified by the parser. Basically, that specific request skips the parsers and potentially other middleware after Beeline middleware.

I've spent some time to investigate what was going on and realized that the stream on the request object was exhausted by the line on the below:

`request.POST.dict()`

I was able to find some more reference when I went deeper:

1) The comment in the source code: https://github.com/encode/django-rest-framework/blob/0cc09f0c0dbe4a6552b1a5bbaa4f7f921270698a/rest_framework/request.py#L326

2) A warning (the green part under `process_view` on the page) on the documentation (this is from Django package for `process_view`, but it still applies): https://docs.djangoproject.com/en/2.2/topics/http/middleware/#process-view

**Comment by tredman** [comment]
Thanks for the report. After discussing internally, we're not sure why `POST.dict()` was added to the instrumentation by default, given that the POST payload could have arbitrary and sensitive information in it. Sounds like we have two good reasons to drop it!

I'm preparing a new release this week to include the change in https://github.com/honeycombio/beeline-python/pull/73. Conveniently, that change also allows users to override the fields that get pulled by default, so users that want the `POST` body can include it if they want to, and we can drop it from the default implementation.

I'll update here when this is ready.

**Comment by tarikozket** [comment]
This has been solved by `2.8.0` update. Thank you very much!
